# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devcontainer < Formula
  desc "CLI for working with Visual Studio Code devcontainers"
  homepage "https://github.com/stuartleeks/devcontainer-cli"
  version "0.1.5001387097"

  on_macos do
    url "https://github.com/stuartleeks/devcontainer-cli/releases/download/v0.1.5001387097/devcontainer-cli_darwin_amd64.tar.gz"
    sha256 "fc1282db36275e8cad388461b6c22462feea019df5c373bb92054bc19ef06eb0"

    def install
      bin.install "devcontainerx"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Devcontainer
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stuartleeks/devcontainer-cli/releases/download/v0.1.5001387097/devcontainer-cli_linux_amd64.tar.gz"
      sha256 "0f36e8932bf265663a409b93f6ecedcab0218cb2c1ee68a3c7f38462d654409f"

      def install
        bin.install "devcontainerx"
      end
    end
  end

  test do
    system "#{bin}/devcontainerx --version"
  end
end
