# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devcontainer < Formula
  desc "CLI for working with Visual Studio Code devcontainers"
  homepage "https://github.com/stuartleeks/devcontainer-cli"
  version "0.1.816111590"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/stuartleeks/devcontainer-cli/releases/download/v0.1.816111590/devcontainer-cli_darwin_amd64.tar.gz"
    sha256 "19ad2a57ee16ebe296c5100a614592f0bb2fc20b13ae695d1f2f63189e94d697"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/stuartleeks/devcontainer-cli/releases/download/v0.1.816111590/devcontainer-cli_linux_amd64.tar.gz"
    sha256 "23a494aee54b2839f7cdc5ef3cdfccc64c5e130ad92689e2c74464d2c4c42d26"
  end

  def install
    bin.install "devcontainer"
  end

  test do
    system "#{bin}/devcontainer --version"
  end
end
