# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevcontainerCli < Formula
  desc "CLI for working with Visual Studio Code devcontainers"
  homepage "https://github.com/stuartleeks/devcontainer-cli"
  version "0.1.801675580"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/stuartleeks/devcontainer-cli/releases/download/v0.1.801675580/devcontainer-cli_darwin_amd64.tar.gz"
    sha256 "9e6acdb85f7daca15fe4628192dd2b6d7b3bda9261793d4608fc3c7c4c1672e4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/stuartleeks/devcontainer-cli/releases/download/v0.1.801675580/devcontainer-cli_linux_amd64.tar.gz"
    sha256 "8ebd80f0b73d75dc93586bc98e8f47fb8aeb63cdcf9fa3cf989cb726895f6909"
  end

  def install
    bin.install "devcontainer-cli"
  end

  test do
    system "#{bin}/devcontainer --version"
  end
end
